Add PyCharm, notebooks, egg-info to gitignore.
WilliamHPNielsen/limnos pull request #6
Opened 2021-05-10 10:33 UTC by petterbejo

Thought it might be a good idea to update the gitignore to avoid things getting messy.

2021-05-16 18:57 UTC, WilliamHPNielsen commented on .gitignore
> +limnos/Untitled.ipynb
Why is `Untitled.ipynb` explicitly ignored? Nothing in limnos generates such a file (right?)

2021-05-16 18:58 UTC, WilliamHPNielsen commented on .gitignore
> +limnos/tests/__pycache__/
It is sufficient to have a single `__pycache__` line; we don't need one for each subfolder.

2021-05-16 18:59 UTC, WilliamHPNielsen commented on .gitignore
> +limnos/.ipynb_checkpoints/
This line is redundant as line 7 already excludes checkpoints.

2021-05-16 19:00 UTC, WilliamHPNielsen requested changes
I left some nitpicky inline comments that I think we should address before merging.

2021-05-26 10:06 UTC, petterbejo commented
I've tidied the gitignore by removing duplicate pycache and checkpoints folders. I've also removed the Untitled.ipynb file from the gitignore and renamed it Limnos-UI since I consider this being more user friendly (I could have made a separate branch for this, but since it's such a small change and it is somehow related to this one, I've included it here).

2021-05-28 12:37 UTC, WilliamHPNielsen approved these changes
Sweet!

2021-05-28 12:38 UTC, merged